version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16
    resource_class: medium  # Sửa indent cho dòng này

jobs:
  build:
    executor: docker-executor  # Image Node.js In-progress
    steps:
      - checkout  # Get source from GitHub
      - setup_remote_docker:  # Activate Docker
          docker_layer_caching: true
      - run:
          name: Install Docker CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t circleci-demo:latest .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

