version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16
    resource_class: medium

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Lấy mã nguồn từ GitHub
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t circleci-demo:latest .
      - run:
          name: Log in to Docker Registry
          command: |
            echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" --username "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Tag Docker Image
          command: |
            docker tag circleci-demo:latest longthanhdam/circleci-demo:latest
      - run:
          name: Push Docker Image to Registry
          command: |
            docker push longthanhdam/circleci-demo:latest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

