version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16
    resource_class: longthanhdam/machine-runner

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Get code  GitHub
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t circleci-demo:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Tag Docker Image
          command: |
            docker tag circleci-demo:latest "$DOCKER_USERNAME/circleci-demo:latest"
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push "$DOCKER_USERNAME/circleci-demo:latest"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

